name: React CLI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
      - uses: arunkkumar2207j/sample-react-only-app@main
        with:
          args: --acl public-read --follow symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secret.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secret.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secret.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-south-1"
          SOURCE_DIR: "build"