name: React CLI

on:
  push:
    branches:
      - "main"

env: 
	CI: false

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build --if-present
      - run: npm test